//
// Generated by JTB 1.3.2
//

package timeline;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(timeline.Visitor v);
   public <R,A> R accept(timeline.GJVisitor<R,A> v, A argu);
   public <R> R accept(timeline.GJNoArguVisitor<R> v);
   public <A> void accept(timeline.GJVoidVisitor<A> v, A argu);
}

