//
// Generated by JTB 1.3.2
//

package timeline;

/**
 * Grammar production:
 * nodeToken -> "Real-time"
 */
public class PlaybackChoiceTime implements Node {
   public NodeToken nodeToken;

   public PlaybackChoiceTime(NodeToken n0) {
      nodeToken = n0;
   }

   public PlaybackChoiceTime() {
      nodeToken = new NodeToken("Real-time");
   }

   public void accept(timeline.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(timeline.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(timeline.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(timeline.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

